### ISSUE TITLE
Broken on Safari

### ISSUE THREAD

**Issue by cmoesel** [FSHSchool/FSHOnline#34]
Oof.  FSH Online doesn't work _at all_ in Safari.  Just a white screen.
![image](https://user-images.githubusercontent.com/2278253/106643750-2c518700-6558-11eb-9297-546b9f573a4b.png)

And here's the console:
<img width="617" alt="image" src="https://user-images.githubusercontent.com/2278253/106644224-d3362300-6558-11eb-9f97-68a2bce009cd.png">

**Comment by jafeltra** [comment]
This issue was caused by the latest version of SUSHI (v1.1.0). That version of SUSHI uses a regular expression lookbehind assertion, which [Safari does not support](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions#browser_compatibility). To resolve this issue, we've updated SUSHI to avoid using that regular expression. The fix was implemented in [this PR](https://github.com/FHIR/sushi/pull/749). When the next version of SUSHI is released, we will update FSH Online to use that version, and this issue should be resolved.
